name: Hello World CI Manual Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t jayamorin/scratch:latest .

      - name: Install dependencies
        run: |
          sudo curl -s -o /usr/local/bin/kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/kubectl
          sudo chmod +x /usr/local/bin/kubectl
          which kubectl

      - name: Decrypt secrets
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mkdir $HOME/secrets
          gpg --help
          gpg --quiet --batch --yes --decrypt --passphrase="$GPG_PASSPHRASE" --output $HOME/secrets/man.txt man.txt.gpg
          cat $HOME/secrets/man.txt

      - name: Update configuration file
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          REDSHIFT_PASSWORD: ${{ secrets.REDSHIFT_PASSWORD }}
        run: |
          sed -i "s|<SECRETS_POSTGRES_PASSWORD>|${POSTGRES_PASSWORD}|g" spark-job.yaml
          sed -i "s|<SECRETS_REDSHIFT_PASSWORD>|${REDSHIFT_PASSWORD}|g" spark-job.yaml
          sed -i 's|<IAM_ROLE>|arn:aws:iam::123456789012:role/RedshiftToS3|g' spark-job.yaml
          cat spark-job.yaml
